export const TAROT_CARDS = [
  'theFool',
  'theMagician',
  'theHighPriestess',
  'theEmpress',
  'theEmperor',
  'theHierophant',
  'theLovers',
  'theChariot',
  'strength',
  'theHermit',
  'wheelOfFortune',
  'justice',
  'theHangedMan',
  'death',
  'temperance',
  'theDevil',
  'theTower',
  'theStar',
  'theMoon',
  'theSun',
  'judgement',
  'theWorld',
] as const
